# Generated by Django 6.0.4 on 2026-04-29 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255)),
                ('p_phone', models.CharField(max_length=10)),
                ('p_email', models.EmailField(max_length=254)),
                ('booked_on', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='dep_name',
            new_name='department',
        ),
        migrations.AddField(
            model_name='doctor',
            name='doc_spec',
            field=models.CharField(default='General', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doc_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctors'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doc_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='doc_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.doctor'),
        ),
    ]
